kind: pipeline
name: default

steps:
  - name: test
    image: pitkley/platformio
    commands:
      - pio upgrade --dev
      - pio update
      - pio test -e native

trigger:
  branch:
    - master
  event:
    - push
